### ISSUE TITLE
"Biggest lodging businesses" query returning no results on the production server 

### ISSUE THREAD

**Issue by bcogrel** [noi-techpark/it.bz.opendatahub.sparql#12]
The regular query "Biggest lodging businesses" on the production server (https://sparql.opendatahub.bz.it/) is run but returns no results.

However, it seems to work fine on the test server (https://sparql.opendatahub.testingmachine.eu/).

**Comment by Piiit** [comment]
@bcogrel I checked the query now. The following minimal query shows the same issue:
```
PREFIX schema: <http://schema.org/>
PREFIX : <http://noi.example.org/ontology/odh#>

SELECT ?r
WHERE {
  ?r a schema:Accommodation  .
}
LIMIT 50
```

The problem seems therefore to be `schema:Accommodation`. I will now see why this is the case...

**Comment by Piiit** [comment]
@bcogrel  I found out that the replication works... that is, `accomodationrooms` and `accomodationroomsopen` are both filled with data on production and testing. However, the `v_accomodationrooms` and `v_accomodationroomsopen` are both empty on production, but not on testing. Could it be that the trigger does not fire somehow?

**Comment by bcogrel** [comment]
Perhaps the trigger did not get fired because it was created after populating the mirror tables. 

Is this database also managed using Flyway?

**Comment by Piiit** [comment]
Yes, it should be exactly the same as in testing...

**Comment by bcogrel** [comment]
Strange. What about recreating this slave DB from scratch?

**Comment by Piiit** [comment]
OK, I know the issue now, we have inside the Flyway migration first the replication and then triggers, this should be inverted, otherwise we produce a race-condition where some records will not be touched by the trigger due to its later installation

**Comment by bcogrel** [comment]
Good catch! Since the number of results looked reasonable for many queries, this order issue in the SQL files didn't pop up to my mind. But, it was unfortunately pure luck…

**Comment by Piiit** [comment]
@bcogrel I fixed the issue now. Also nginx works, have not changed anything there. It worked already as expected. 

Please test on https://sparql.opendatahub.testingmachine.eu/

- Do you think that the nginx configuration is still wrong?
- If you give me your OK, I will release these changes on production

**Comment by bcogrel** [comment]
Hi @Piiit, it looks good thanks! You have my OK.

The cache is working for the queries. For instance, if you run this query 2 times in 10 seconds, you should have the same results:

```sparql
SELECT (UUID() AS ?u) WHERE {
  ?sub ?pred ?obj .
} 
LIMIT 10
```
Sorry, I was hoping to go below 100 ms, but that's simply due to the network.

Thanks

**Comment by Piiit** [comment]
@bcogrel I am happy with that result... so thanks for your work. I will put it into production now!
