### ISSUE TITLE
Monitoring and logging, to understand how many queries are made and how often the endpoint is used

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.sparql#14]
Virtual Knowledge Graph usage elicitation with a Grafana dashboard

**Comment by Piiit** [comment]
@sseppi Do you need an estimate of the effort for this task?

**Comment by sseppi** [comment]
> @sseppi Do you need an estimate of the effort for this task?

@Piiit this would be great in order to understand how much effort we have to invest in order to introduce this functionality.

**Comment by Piiit** [comment]
@sseppi  Perfect, so you can please move it to TODO or ESTIMATE EFFORT column on https://github.com/orgs/noi-techpark/projects/13, dunno what is needed

**Comment by Piiit** [comment]
To understand it better, the source code changes will be made by Ontopic, it would just be the integration in our existing systems and create a dashboard either together with Ontopic, or to give them access to our elasticsearch and kibana/grafana

**Comment by Piiit** [comment]
@alexlanz Let me know, what you would need from an external company

**Comment by alexlanz** [comment]
I think we could simply analyze the HTTP access logs. Or what do you think? Because every query should be an HTTP request.

**Comment by Piiit** [comment]
Exactly, ontopic will provide some json logs to the stdout with data they need for their dashboard. They will figure that out, and then you simply need to setup the log shipping from vkg to elastic, and maybe enable visualizations on grafana?

**Comment by alexlanz** [comment]
I took a look at the project and I think the following steps are required:

1. Migrate project from docker01 to docker02 and adjust Docker setup (AboutBits)
2. Adjust logging to log to stdout in json format including access logs (Ontopic)
  An example can be found here: https://github.com/noi-techpark/java-boilerplate/pull/2/files#diff-892a99aa999cfc571ab82396c32ba5de
3. Create Grafana dashboard to show usage of tool (AboutBits)

Estimaton for our work: 4-8 hours

**Comment by Piiit** [comment]
@bcogrel @ghxiao Hi, we asked Aboutbits to integrate the VKG logs into our infrastructure. For that to work, they would need a minimal logging setup on your side. It is sufficient to just write logs to stdout, they must be JSON format. The example can be seen in the comment above.
If you have any questions please just reply to this comments...

Cheers,
Peter

**Comment by Piiit** [comment]
@phopfgartner wrote in a Kanban card:

----
Developing the logging infrastructure within Ontop for detailed logging, as described during the meeting.
Given the general nature of this functionality and the future reuse, Ontopic will participate to 50% to this effort.
This effort is estimated at 60-80 development hours for generating the logs from within Ontopic and writing them to STDOUT of the Docker container.

----
I remove the card, so we can follow the progress with this issue...

**Comment by bcogrel** [comment]
@Piiit , we are working on adding some simple JSON objects at several moments of the query processing: 
  1. after reformulating the query (into SQL), 
  2. after the result set unblocks (first batch of results or all results, depending if the streaming mode is enabled or not)
  3. after fetching the last result

So as to be able to join them, all these log entries will share the same queryId. 

Would that be ok for you?

I am planning to do a PR during the week-end or on Monday, with this first version of the logging included in the snapshot Docker image of Ontop.

**Comment by bcogrel** [comment]
The snapshot Docker image of Ontop now offers a preliminary form of logging and PR #15 activates this option. Please have a try.

**Comment by bcogrel** [comment]
See also #16 for more recent changes

**Comment by Piiit** [comment]
@bcogrel Thanks, I merged the PR now and we got some logs in kibana... Now we need to see, what information we would exactly need in the logs for some useful statistics.
