### ISSUE TITLE
See if we can open the Kibana dashboard only for external contributors (example, VKG for ontopic)

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.sparql#24]
https://logs.opendatahub.bz.it/spaces/space_selector

![image](https://user-images.githubusercontent.com/6096063/99278101-ef1a0a80-282e-11eb-8938-1f6ba896b3b4.png)

**Comment by alexlanz** [comment]
This should be solved now. I gave the credentials to the developers, so that they can forward it to Ontop.
