### ISSUE TITLE
Problem for getting image URLs on the test and production servers

### ISSUE THREAD

**Issue by bcogrel** [noi-techpark/it.bz.opendatahub.sparql#25]
Hi,

The following SPARQL query returns an error both on the test and production servers:
```sparql
PREFIX schema: <http://schema.org/>
SELECT * WHERE {
  ?h schema:image ?im .
} 
LIMIT 26
```
The error (from Postgres) is:
```
it.unibz.inf.ontop.exception.OntopQueryEvaluationException: org.postgresql.util.PSQLException: ERROR: invalid value ":0" for "MI"
  Detail: Value must be an integer.
```

I didn't manage to reproduce the issue on my machine, even with a newer dump.

The requested triple patterns uses the following SQL query in the mapping:
```sql
SELECT  "accommodationsopen_Id" as id , "ImageUrl" as image from "v_accommodationsopen_ImageGallery" 
WHERE TO_TIMESTAMP("ValidTo", 'YYYY-MM-DDTHH24:MI:SS') > NOW() AND TO_TIMESTAMP("ValidFrom", 'YYYY-MM-DDTHH24:MI:SS') < NOW()
```

Could you please have a look? Is there some invalid values in the DB that need to be filtered out?

**Comment by Piiit** [comment]
@bcogrel This error means that the view `v_accommodationsopen_ImageGallery` which contains `ValidTo` and `ValidFrom` text fields, contain values which are not translatable with `TO_TIMESTAMP`. Since those fields are just strings, there is no checking if the time/date parsing is correct. So your assumption is correct, that there are invalid values in the DBs (data::jsonb). Do you need further information?

**Comment by Piiit** [comment]
@RudiThoeni There are maybe wrong values in the json of accommodationsopen regarding time values in PG... could you please have a look?

**Comment by bcogrel** [comment]
Thanks @Piiit for the explanation.  What are these values? Is there is a simple way to filter them out?

**Comment by RudiThoeni** [comment]
Hi
I take the ValidFrom and ValidTo data as it comes from the source LTS.... There are cases where ValidFrom and ValidTo are null

**Comment by RudiThoeni** [comment]
at example here 
http://tourism.opendatahub.bz.it/api/Accommodation?fields=Id,ImageGallery&pagesize=1000

**Comment by Piiit** [comment]
@bcogrel Could you take care of these possibilities and eventually fix them, when you do the integration from our logical replication to the proper views and tables? Would that be feasible?

**Comment by bcogrel** [comment]
Hi,

I will do the cleaning at the mapping level, as our derived tables are automatically generated. I am thinking of using a regular expression before converting the string to a timestamp.

One question: in the absence of ValidFrom and ValidTo, shall we consider the image URL?

Best,
Benjamin

**Comment by RudiThoeni** [comment]
Hi

yes consider it because ValidFrom and ValidTo are not constraints....
and if there are more images please take the image with lowest ListPosition 

cheers
Rudi

**Comment by Piiit** [comment]
@RudiThoeni @bcogrel 
Hi, I will let you work on this now, please ping me, when you are done with the issue, that is, when you open a PR that solves it... 

In the meantime I will start with the logical replication of mobility.....

**Comment by skomlaebri** [comment]
Hi, 
I just opened the PR to solve the issue.
As we said before we consider the images in the valid timeframe and the ones without the validity information. We show as well the images where the time/date parsing is invalid. If there are more images we take the image with the lowest ListPosition.

**Comment by Piiit** [comment]
@skomlaebri @bcogrel @RudiThoeni 
This works now and is live on testingmachine, thanks for the PR

https://sparql.opendatahub.testingmachine.eu/

**Comment by bcogrel** [comment]
Hi @Piiit , I think we are done with this issue, am I right? Can we close it?

**Comment by Piiit** [comment]
@bcogrel Yes, we are done, just not released yet... so for us it is still open, but for Ontopic it is "done"... (see Kanban)... I will release it together with the changes of the logical replication...

**Comment by Piiit** [comment]
@bcogrel @skomlaebri @RudiThoeni Finally released into production...
