### ISSUE TITLE
As an Open Data Hub consumer, I want to retrieve also closed mobility data from the knowledge graph, and have authentication

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.sparql#36]
- [x] Add the login mechanism to the testing environment @Piiit 
- [x] Remove Guest from title: Open Data Hub Knowledge Graph Portal (Guest)  <-- if we see that title, could it be, that we operate on the wrong VKG?
- [x] Add a logout button (we need to login with another user sometimes)
- [x] Add a profile somewhere or a login indicator (in Yasgui if possible, or as frame?) Please check if it is feasible...
- [x] Inactivity should logout after short time (like 5-10 minutes; best would be a configuration option)
  >  This functionality has still some problems, see comments below
- [x] Add a mobility example in Yasgui that shows restricted data
  > I use "Sensor/ObservableProperty/Observation statistics" for that purpose, which worked

**Comment by Piiit** [comment]
@jcte02 The login seems to work now, but I still see "Open Data Hub Knowledge Graph Portal (Guest)" as title... I think we can remove (Guest) here. Another thing is that I cannot logout and do not have a profile indication anywhere. Would that be possible in Yasgui? The logout is important, because when someone has more than one account or the computer is used by more than one person, we need to switch users. I move this ticket back to TODO... and update the initial comment with some work items.

**Comment by Piiit** [comment]
Tested on https://sparql.opendatahub.testingmachine.eu/restricted

**Comment by jcte02** [comment]
@Piiit The logout is already implemented by the proxy, but I agree a logout button is in order.
Regarding the profile indication, we are limited to what the authentication proxy returns to us, namely username, email, user id and group membership status. It's not much but I think we can provide a basic profile indicator like `$USERNAME ($EMAIL)` if it's ok with you. Let me know if you think group membership or user id could be also of interest to display.
Regarding you secod-last point: we can't actually monitor inactivity per-se, but we can control the expire time of the authenticated sessions. We can set up the proxy to refresh the session every time a request is made. So after a configurable period of not making requests your session expires and you have to authenticate again. This is not proper inactivity tracking (the user could be at their desk but doing something else in the meantime) but I think it's approriate for your situation. I will expose a new environment variable to control session expiration and update the documentation accordingly.
I will open a new PR with all these changes once I have test them locally.

**Comment by Piiit** [comment]
@jcte02 Thank you... I will wait for the PR then

**Comment by Piiit** [comment]
@jcte02 After expiration of the token I get a 500 server error by nginx. Opening the url in another browser starts the login process/redirect again... I must delete all cache to be able to login again in the same window. Also Yasgui sometimes just returns an error in the response pane below and does not show a re-login or expiration notification...

**Comment by Piiit** [comment]
Found some logs:

```
oauth2_1       | [2021/04/09 13:15:11] [stored_session.go:122] Refreshing 29m44.268090786s old session cookie for Session{email:p.moser@noi.bz.it user:c3284900-668a-4ef2-ad0e-67e0e7ebeaec PreferredUsername:pmoser token:true id_token:true created:2021-04-09 12:45:26.731909214 +0000 UTC expires:2021-04-09 12:50:26.729842031 +0000 UTC refresh_token:true groups:[/Email Notification Group /NOI Developers /VKG Full Access]} (refresh after 1m0s)
nginx_1        | 34.255.139.75 - - [09/Apr/2021:13:15:11 +0000] "GET /restricted/ HTTP/1.1" 500 177 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0"
nginx_1        | 2021/04/09 13:15:11 [error] 9#9: *8080 upstream sent too big header while reading response header from upstream, client: 34.255.139.75, server: , request: "GET /restricted/ HTTP/1.1", subrequest: "/oauth2/auth", upstream: "http://192.168.96.3:4180/oauth2/auth", host: "sparql.opendatahub.testingmachine.eu"
nginx_1        | 2021/04/09 13:15:11 [error] 9#9: *8080 auth request unexpected status: 502 while sending to client, client: 34.255.139.75, server: , request: "GET /restricted/ HTTP/1.1", host: "sparql.opendatahub.testingmachine.eu"
oauth2_1       | [2021/04/09 13:15:11] [oidc.go:128] refreshed session: Session{email:p.moser@noi.bz.it user:c3284900-668a-4ef2-ad0e-67e0e7ebeaec PreferredUsername:pmoser token:true id_token:true created:2021-04-09 13:15:11.772468508 +0000 UTC m=+80285.410429577 expires:2021-04-09 13:20:11.772062136 +0000 UTC m=+80585.410023250 refresh_token:true groups:[/Email Notification Group /NOI Developers /VKG Full Access]}
oauth2_1       | 192.168.96.4:58152 - p.moser@noi.bz.it [2021/04/09 13:15:11] sparql.opendatahub.testingmachine.eu GET - "/oauth2/auth" HTTP/1.0 "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0" 202 0 0.050
oauth2_1       | [2021/04/09 13:15:11] [session_store.go:164] WARNING: Multiple cookies are required for this session as it exceeds the 4kb cookie limit. Please use server side session storage (eg. Redis) instead.
```

Seems that the response headers are too big... this afaik happens when refreshing the login token... Please check

**Comment by jcte02** [comment]
I cannot check as I don't have client access to the Keycloak server, but indeed the session seems to exceed the 4kb cookie limit. I will prepare a PR to enable server-side session storage using Redis.

**Comment by Piiit** [comment]
@jcte02 Works! Thanks for all!

**Comment by Piiit** [comment]
@jcte02 The work of Ontopic is done, but I keep it open for our purposes, since we still need to put it into production
