### ISSUE TITLE
Changes in the opentables/tables strategy on Postgres Tourism DB should be reflected inside the Ontop mappings

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.sparql#45]
Original Email by Rudi from 4/6/2021:

![Selection_072](https://user-images.githubusercontent.com/6096063/121493054-b95d8e80-c9d7-11eb-9bb5-a47539fdc114.png)

**Comment by Piiit** [comment]
@RudiThoeni @sseppi  FYI

**Comment by Piiit** [comment]
What should we do with closed data on tourism? Should we expose that data on our /restricted VKG?

**Comment by bcogrel** [comment]
Hi, thanks for the update, that's an interesting move. 

At the moment closed data on tourism is not mapped. Making it available to  /restricted would be a new feature.

@Piiit , could you please send us a new dump of the database? Non-"open" tables are empty in our local test image. Ideally, it would great for us to have also closed data. We would then exclude them from the public Docker database image, while keeping it in our private one, as we did for mobility data.

Benjamin

**Comment by Piiit** [comment]
@bcogrel @jcte02 
We updated the CD pipelines to automatically deploy the new VKG with Postgres `virtual-knowledge-graph.co90ybcr8iim.eu-west-1.rds.amazonaws.com/vkg`, but I get an error:

**Error: Unable to find attribute "AccoDetail-de-Email"**

```
ontop-guest_1  | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
ontop-guest_1  | 09:40:16.461 |-ERROR in o.s.boot.SpringApplication - Application run failed
ontop-guest_1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sparqlQueryController' defined in URL [jar:file:/opt/ontop/lib/ontop-endpoint-4.2.0.jar!/it/unibz/inf/ontop/endpoint/controllers/SparqlQueryController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'setupVirtualRepository' defined in class path resource [it/unibz/inf/ontop/endpoint/beans/OntopVirtualRepositoryBean.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [it.unibz.inf.ontop.rdf4j.repository.impl.OntopVirtualRepository]: Factory method 'setupVirtualRepository' threw exception; nested exception is org.eclipse.rdf4j.repository.RepositoryException: it.unibz.inf.ontop.exception.InvalidMappingSourceQueriesException: Error: Unable to find attribute "AccoDetail-de-Email" (available attributes are ["Id",

.......

```

I think we might need to update some mappings... 

If we need to update triggers or table definitions we need to setup flyway again. Otherwise we are never sure which exact schema version is installed.

**Comment by bcogrel** [comment]
@Piiit , I have prepared a PR for this: https://github.com/noi-techpark/it.bz.opendatahub.sparql/pull/59

Some the changes it brings to the mapping are temporary, and will need to be reverted once Flyway will have been run over the new database.

**Comment by RudiThoeni** [comment]
closed due to inactivity
