### ISSUE TITLE
As a maintainer of the Virtual Knowledge graph I want to have a staging and production environment on a smaller instance without logical replication

### ISSUE THREAD

**Issue by Piiit** [noi-techpark/it.bz.opendatahub.sparql#49]
CLOSED, because we plan to dismiss the SparQL End Point.

-----------------------------

Deadline: 30 of June 2022

I wrote a mail to Ontopic to outsource this as a R&D project. Kickoff on Feb 22...

Some technical To Dos:
- [x] NOI: New VKG Postgres DB on our AWS/RDS
- [x] NOI: Full Access to the VKG Postgres for Ontopic
- [x] NOI: Read Access to tourism and mobility production dbs for sync
- [x] ONTOPIC: Synchronization mechanism from mobility and tourism to vkg
- [ ] NOI + ONTOPIC: Monitoring of the browsable KG and the sparql endpoints and landingpages
- [ ] ONTOPIC: Updates the services (that is deploys their software first on testing and then production via git pull)
- [ ] NOI: updates the server and eventually upgrades resources if needed (on request by Ontopic)

**UPDATE 2022-05-26**
Ontopic is done with testing, should we create one or two databases fully synced with all data of tourism and mobility (production + testing), or just a single one for production and eventually a testing DB with only 3 months of data.

Having both is expensive, having only one is eventually dangerous for testing new features.

Needs a decision

----

**OLD TODOS**
```
- [x] Reactivate the testing instance
- [x] Write email to gather feedback
- [x] create sync script 
- [ ] dockerize the script and schedule it (clean temp files)
- [ ] write json as log files and show errors if something is not working
- [ ] collect the json and provide grafana dashboard and alerting
- [ ] write documentation
```
We will not "Reactivate the logical replication on production", we have a prototype of a sync script now

A minimal docker file could start like:

```dockerfile
FROM alpine:3.10
RUN apk --no-cache add postgresql-client
```

**Comment by ohnewein** [comment]
------------------------------------  NOI  -----------------------------------
- production tourism DB
- production mobility DB

=> replication for tourism + script for mobility (push data to Ontopic DB)
----------------------------------------------------------------------------------------------


------------------------------------  ONTOPIC  -----------------------------------
- Ontopic DB (tourism + mobility) | Ontopic has full access and manages this server and DB
- SparQL installation reading from Ontopic DB
----------------------------------------------------------------------------------------------

**Comment by Piiit** [comment]
@jcte02 I had a second thought about test DBs, what if, we do not sync the "bigTables" (`measurementhistory` and `measurementstringhistory`) as you describe them in test dbs, but just handle them like small tables, and copy/paste data from the `measurement` and `measurementstring` tables respectively. So we always have a small test instance, that does not cost a lot, but we could still have automatic deployments for staging and production...

I would therefore add another CLI parameter, for example `--no-big-tables` or `--test-only` which does the following:
1) "small-table" delete/insert of `measurement` to `measurementhistory`
2) "small-table" delete/insert of `measurementstring` to `measurementstringhistory`
3) skip of all "big-tables"

What do you think?

**Comment by jcte02** [comment]
@Piit I talked with @bcogrel and our worry is that by not synchronizing the big tables in the test database we become unable to test the performance of the data at scale, i.e. the SPARQL endpoint could work well in the test database due to the small data but become unusable once exposed to the production data.
If having an exact copy of the production database is not a possibility, then I think we can settle for your idea.

**Comment by Piiit** [comment]
@jcte02 We want to avoid the full copy, because we lack users at the moment. If you want to test the whole I think, we might be able to help you setup everything on your machine or server with the whole dataset. If you just want to test readonly queries or mappings you could simply point to the production DB from your own (local) testing sparql endpoint. 

The test db should just be a functional test... for the moment at least, if in the future, we gain additional users we can rethink this approach

**Comment by RudiThoeni** [comment]
last PR from ontopic worked now the sync script has to be used

First Import

https://github.com/noi-techpark/it.bz.opendatahub.sparql/tree/main/infrastructure/utils/mobility-initial-import

Sync Script

https://github.com/noi-techpark/it.bz.opendatahub.sparql/tree/main/infrastructure/docker/mobility-sync
